#!/bin/bash

set -eu

log=~/irc2mail.log
cd ~/irc2mail/
config=~/.irc2mail.pl
cmd=$(printf './irc2mail %q' "$config")

stop () {
    echo "`date` stop" >> "$log"
    daemonize --stop -- $cmd
}

start () {
    echo "`date` start" >> "$log"
    daemonize --bg --out "$log" -- $cmd
}

case "$1" in
    stop)
    stop
    ;;
    start)
    start
    ;;
    restart)
    stop || true
    start
    ;;
    *)
    echo "$0 start|stop"
    ;;
esac

